FROM amazoncorretto:11-alpine AS builder

RUN apk update \
 && apk add bash

# scala setup
ENV SCALA_VERSION=2.13.5 \
    SCALA_HOME=/usr/share/scala \
    SBT_VERSION=1.5.0 \
    SBT_HOME=/usr/share/sbt

# install scala
RUN cd /tmp \
 && wget "https://downloads.typesafe.com/scala/${SCALA_VERSION}/scala-${SCALA_VERSION}.tgz" \
 && tar xzf scala-${SCALA_VERSION}.tgz \
 && rm /tmp/scala-${SCALA_VERSION}/bin/*.bat \
 && mkdir ${SCALA_HOME} \
 && mv /tmp/scala-${SCALA_VERSION}/bin /tmp/scala-${SCALA_VERSION}/lib ${SCALA_HOME}/ \
 && ln -s ${SCALA_HOME}/bin/* /usr/bin/ \
 && rm -rf /tmp/*

# install sbt
RUN cd /tmp \
 && wget https://github.com/sbt/sbt/releases/download/v${SBT_VERSION}/sbt-${SBT_VERSION}.tgz \
 && tar xzf sbt-${SBT_VERSION}.tgz \
 && mkdir ${SBT_HOME} \
 && mv sbt/* ${SBT_HOME}/ \
 && ln -s ${SBT_HOME}/bin/* /usr/bin \
 && rm -rf /tmp/*

# install matterminder
WORKDIR /build
COPY . ./
RUN sbt dist





FROM amazoncorretto:11-alpine
RUN apk update \
 && apk add bash \
 && apk add tzdata

WORKDIR /app
COPY --from=builder /build/target/universal/matterminder-* ./matterminder.zip
RUN unzip matterminder.zip \
 && rm matterminder.zip \
 && mv matterminder-*/* ./ \
 && rm -r matterminder-* \
 && chmod u+x bin/matterminder

CMD ["bin/matterminder"]
EXPOSE 9000