version: "2"
services:

  mattermost:
    container_name: matterminder_mattermost-preview
    image: mattermost/mattermost-preview
    expose:
      - 8065
    ports:
      - 8065:8065

  matterminder-db:
    container_name: matterminder_db
    image: postgres:9-alpine
    volumes:
      - ../data:/var/lib/postgresql/data/persistent_data:rw
    environment:
      - POSTGRES_USER=matterminder
      - POSTGRES_PASSWORD=_someSecretPostgresPassword937
      - POSTGRES_DB=matterminder
      - PGDATA=/var/lib/postgresql/data/persistent_data
    expose:
      - 5432
    ports:
      - 5432:5432

  matterminder:
    container_name: matterminder
    build:
      context: ../
      dockerfile: docker/Dockerfile_Matterminder
    environment:
      - JAVA_OPTS=-Dplay.crypto.secret="secret.matterMinder_4ppl1c4t10nS3cr3t" #-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005
      - TZ=Europe/Berlin
      - MATTERMINDER_MATTERMOST_SERVER=mattermost
      - MATTERMINDER_MATTERMOST_PORT=8065
      - MATTERMINDER_MATTERMOST_PROTOCOL=http
      - MATTERMINDER_SLASH_COMMAND_TOKEN_TO_WEBHOOK_KEY_MAPPINGS=zf3iqe6ifjdtdef3k8cum6hsfa:obci5q1xd3n1zk3ipttaa6iwsc#guewgmwaa7858cj74ufamfnwwc:t3u415ozjigb9nb6b94cxg4are
      - MATTERMINDER_POSTGRES_SERVER=matterminder-db
      - MATTERMINDER_POSTGRES_DATABASE=matterminder
      - MATTERMINDER_POSTGRES_USER=matterminder
      - MATTERMINDER_POSTGRES_PASSWORD=_someSecretPostgresPassword937
    depends_on:
      - mattermost
      - matterminder-db
    expose:
      - 9000
    #ports:
    #  - 5005:5005
    stdin_open: true
      
