version: "2"
services:

  mattermost:
    container_name: matterminder_mattermost-preview
    image: mattermost/mattermost-preview
    expose:
      - 8065
    ports:
      - 8065:8065

  matterminder-db:
    container_name: matterminder_db
    image: postgres:9-alpine
    environment:
      - POSTGRES_USER=matterminder
      - POSTGRES_PASSWORD=_someSecretPostgresPassword937
      - POSTGRES_DB=matterminder
    expose:
      - 5432

  matterminder:
    container_name: matterminder
    build:
      context: ../
      dockerfile: docker/Dockerfile_Matterminder
    environment:
      - MATTERMINDER_MATTERMOST_SERVER=mattermost
      - MATTERMINDER_MATTERMOST_PORT=8065
      - MATTERMINDER_MATTERMOST_PROTOCOL=http
      - MATTERMINDER_OUTGOING_KEY=t3u415ozjigb9nb6b94cxg4are
      - MATTERMINDER_POSTGRES_SERVER=matterminder-db
      - MATTERMINDER_POSTGRES_DATABASE=matterminder
      - MATTERMINDER_POSTGRES_USER=matterminder
      - MATTERMINDER_POSTGRES_PASSWORD=_someSecretPostgresPassword937
    depends_on:
      - mattermost
      - matterminder-db
    expose:
      - 9000
    stdin_open: true
      
